### ISSUE TITLE
Program.cs contains Environment.Exit

### ISSUE THREAD

**Issue by skahwah** [RikunjSindhwad/MSSQL-Attacker#1]
Line 73 for reference.

If authentication fails, it is likely that beacon, or whatever process MSSQL-Attacker is running in will exit. 

Reference: https://www.mdsec.co.uk/2020/08/massaging-your-clr-preventing-environment-exit-in-in-process-net-assemblies/

**Comment by RikunjSindhwad** [comment]
It will be improved/fixed in the next release.
