### ISSUE TITLE
Error when I activate xp_cmdshell on linked server 

### ISSUE THREAD

**Issue by LyesH4ck** [RikunjSindhwad/MSSQL-Attacker#3]
Hello, 

I would like to report an issue when I try to enable XP_CMDSHELL on a linked server.
A simple screenshot to describe the issue.

Thank you.

![image](https://user-images.githubusercontent.com/10633285/187975575-daed9b31-a71d-4456-924c-400a4d722bc3.png)

**Comment by RikunjSindhwad** [comment]
I will check and fix soon as possible, What I see here is, You can execute queries however you don't have enough privileges to enable cmdshell. can you give it a try to do it manually. Also try with -ImpersonateSA or DBO

**Comment by LyesH4ck** [comment]
Thanks for your response.
I wasn't sure if it was a permission issue :)

I thought I was Sysadmin on this instance.. But not...
I've tested the link with PowerUpSQL.

![image](https://user-images.githubusercontent.com/10633285/187984698-ad2431a1-f94c-462f-a14e-50ac08d1e390.png)

Thank you :)

**Comment by RikunjSindhwad** [comment]
Patched in new release...  V2
Please spend some more time to find issues as such.

**Comment by RikunjSindhwad** [comment]
Thanks for the image https://github.com/RikunjSindhwad/MSSQL-Attacker/issues/3#issuecomment-1234628298
I will add sysadmin check in the coming releases
